<?php

namespace ContainerNHSTNgp;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_KlF2JmFService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.KlF2JmF' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.KlF2JmF'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', true],
            'mailer' => ['privates', 'mailer.mailer', 'getMailer_MailerService', true],
            'service' => ['privates', '.errored..service_locator.KlF2JmF.App\\Entity\\Service', NULL, 'Cannot autowire service ".service_locator.KlF2JmF": it needs an instance of "App\\Entity\\Service" but this type has been excluded in "config/services.yaml".'],
        ], [
            'entityManager' => '?',
            'mailer' => '?',
            'service' => 'App\\Entity\\Service',
        ]);
    }
}
