<?php

namespace ContainerNHSTNgp;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_FH8zyAZService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.fH8zyAZ' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.fH8zyAZ'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'appointment' => ['privates', '.errored..service_locator.fH8zyAZ.App\\Entity\\Appointment', NULL, 'Cannot autowire service ".service_locator.fH8zyAZ": it needs an instance of "App\\Entity\\Appointment" but this type has been excluded in "config/services.yaml".'],
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', true],
            'mailer' => ['privates', 'mailer.mailer', 'getMailer_MailerService', true],
            'twilioService' => ['privates', 'App\\Service\\TwilioService', 'getTwilioServiceService', true],
        ], [
            'appointment' => 'App\\Entity\\Appointment',
            'entityManager' => '?',
            'mailer' => '?',
            'twilioService' => 'App\\Service\\TwilioService',
        ]);
    }
}
