<?php

namespace ContainerNHSTNgp;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getTestTwilioCommandService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Command\TestTwilioCommand' shared autowired service.
     *
     * @return \App\Command\TestTwilioCommand
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'symfony'.\DIRECTORY_SEPARATOR.'console'.\DIRECTORY_SEPARATOR.'Command'.\DIRECTORY_SEPARATOR.'Command.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Command'.\DIRECTORY_SEPARATOR.'TestTwilioCommand.php';

        $container->privates['App\\Command\\TestTwilioCommand'] = $instance = new \App\Command\TestTwilioCommand(($container->privates['App\\Service\\TwilioService'] ?? $container->load('getTwilioServiceService')));

        $instance->setName('app:test-twilio');
        $instance->setDescription('Test Twilio SMS sending functionality');

        return $instance;
    }
}
