<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerNHSTNgp\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerNHSTNgp/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerNHSTNgp.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerNHSTNgp\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerNHSTNgp\App_KernelDevDebugContainer([
    'container.build_hash' => 'NHSTNgp',
    'container.build_id' => '5fe25c1d',
    'container.build_time' => 1751725374,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerNHSTNgp');
